In [ ]:
import string

text = """
Ugh... The deliveries were DELAYED!!
I seriously hate waiting... #annoyed praveen
"""

In [ ]:
text_lower = text.lower()
print(text_lower)

ugh... the deliveries were delayed!!
i seriously hate waiting... #annoyed praveen

In [ ]:
table = str.maketrans("aeiou", "*****")
text = "hello world"

print(text.translate(table))

h*ll* w*rld

In [ ]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [ ]:
translator = str.maketrans('', '', string.punctuation)
clean_text = text_lower.translate(translator)

print(string.punctuation)
print(" ")
print("Original:", text)
print("Cleaned: ", clean_text)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

Original: hello world
Cleaned:
ugh the deliveries were delayed
i seriously hate waiting annoyed praveen

In [ ]:
print(clean_text)

ugh the deliveries were delayed
i seriously hate waiting annoyed praveen

In [ ]:
print(clean_text.split(' '))

['\nugh', 'the', 'deliveries', 'were', 'delayed', '\ni', 'seriously', 'hate', 'waiting', 'annoyed', 'praveen\n']

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
print(tokenizer.tokenize(clean_text))

['u', '##gh', 'the', 'deliveries', 'were', 'delayed', 'i', 'seriously', 'hate', 'waiting', 'annoyed', 'pr', '##ave', '##en']

In [ ]:
print(clean_text.split(' '))

['\nugh', 'the', 'deliveries', 'were', 'delayed', '\ni', 'seriously', 'hate', 'waiting', 'annoyed', 'praveen\n']

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
print(stopwords.words('english'))
print(len(stopwords.words('english')))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
198

In [ ]:
tokens = clean_text.split(' ')
print(tokens)

['\nugh', 'the', 'deliveries', 'were', 'delayed', '\ni', 'seriously', 'hate', 'waiting', 'annoyed', 'praveen\n']

In [ ]:
print(len(tokens))

11

In [ ]:
non_stop_words = []
for token in tokens:
  if token not in stopwords.words('english'):
    non_stop_words.append(token)

print(non_stop_words)
print(len(non_stop_words))

['\nugh', 'deliveries', 'delayed', '\ni', 'seriously', 'hate', 'waiting', 'annoyed', 'praveen\n']
9

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
from nltk.stem import PorterStemmer, WordNetLemmatizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ["deliveries" , "waiting" , "delayed" , "studies"]

for word in words:
  print(f"{word} | {stemmer.stem(word)} | {lemmatizer.lemmatize(word)}")

deliveries | deliveri | delivery
waiting | wait | waiting
delayed | delay | delayed
studies | studi | study

**Bag of Wrords**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

vectorizer = CountVectorizer()

corpus = [
    "Win free money",
    "Win huge money",
    "The deliveries were delayed"
]

sent_vector = vectorizer.fit_transform(corpus)
print(sent_vector.toarray())

print()

pd.DataFrame(sent_vector.toarray(),
             columns=vectorizer.get_feature_names_out())

[[0 0 1 0 1 0 0 1]
 [0 0 0 1 1 0 0 1]
 [1 1 0 0 0 1 1 0]]

   delayed  deliveries  free  huge  money  the  were  win
0        0           0     1     0      1    0     0    1
1        0           0     0     1      1    0     0    1
2        1           1     0     0      0    1     1    0

**Vector Embedding**

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
words = ["King" , "Queen" , "Apple"]
pd.DataFrame(model.encode(words))

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.059599,0.050512,-0.069510,0.079680,-0.046748,0.000989,0.079043,-0.012739,0.058396,-0.031402,...,0.087435,0.003265,-0.026208,0.038800,-0.073888,-0.015720,0.164207,-0.030399,-0.001087,-0.015922
1,0.035487,-0.065605,-0.009935,0.031590,-0.013387,0.028892,0.116708,-0.034309,0.054405,-0.005583,...,0.023805,0.011133,-0.062244,0.011289,-0.058576,0.026038,0.091385,-0.053889,-0.031242,-0.086961
2,-0.006138,0.031012,0.064794,0.010941,0.005267,-0.047476,0.081203,0.028981,0.066762,0.030300,...,0.013608,-0.019269,0.021374,-0.099896,-0.067282,0.076550,0.160245,-0.048190,0.073520,0.089539

**Padding**

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I love AI",
    "The deliveries were delayed",
    "Win free money"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

print()

sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

{'i': 1, 'love': 2, 'ai': 3, 'the': 4, 'deliveries': 5, 'were': 6, 'delayed': 7, 'win': 8, 'free': 9, 'money': 10}

[[1, 2, 3], [4, 5, 6, 7], [8, 9, 10]]

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_sequences = pad_sequences(sequences)
print(padded_sequences)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  8  9 10]]